name: Generate GitHub Stats SVGs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate General Stats Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: 'username=Abdullah-AYP&show_icons=true&theme=radical&hide_border=true&bg_color=0D1117'
          path: github-stats.svg
          token: ${{ secrets.PAT_1 }}

      - name: Generate Top Languages Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: 'username=Abdullah-AYP&layout=compact&theme=radical&hide_border=true&bg_color=0D1117'
          path: top-langs.svg
          token: ${{ secrets.PAT_1 }}

      - name: Commit and Push SVGs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg top-langs.svg
          git commit -m "Update GitHub stats SVGs" || echo "No changes to commit"
          git push
